---
title: "ESM 244 - Final"
author: "Kristan Culbert"
date: "February 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include = FALSE}
# load packages

library(tidyverse)
library(janitor)

```

```{r}
# Load data

transect <- read_csv("transect.csv") %>% 
  clean_names()


avian <- read_csv("avian.csv")%>% 
  clean_names()

#load key for species

species_key <- read_csv("lookup_species.csv") %>% 
  clean_names()

```

```{r}
#Data wrangling for transect data - are we using this for wrack data only?

transect_select <- transect %>% 
  select(id, survey_date, transect_block, wrack, seagrass, wrack_assessed) %>% 
  rownames_to_column()

View(transect_select)

```

```{r}
#Data wrangling for avian data - double-check variables that we want to keep

avian_select_2 <- avian %>%
  select(survey_date, species, count,transect_block) %>% 
  rownames_to_column() %>% 
  arrange(species) 

View(avian_select_2)

#Quick histogram

avian_hist <- ggplot(avian_select2, aes(x = count)) +
  geom_histogram(aes(fill = species)) +
  facet_wrap(~species, scales = "free")

avian_hist


```

